### Create product
POST http://localhost:8005/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 Description",
    "price": 100
}

### Get Products
GET http://localhost:8005/products
Content-Type: application/json
