import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import AppProviders from './app.providers'
import { Container, CssBaseline } from '@mui/material'
import Header from './_components/header'
import authenticated from './_action/check-auth.action'

const geistSans = localFont({
  src: './_fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './_fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const isAuthenticated = await authenticated()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/**
         * ensure that the styles are appended to the <head> and not rendering in the <body>
         **/}
        <AppProviders authenticated={isAuthenticated}>
          <CssBaseline />
          <Header />
          <Container>{children}</Container>
        </AppProviders>
      </body>
    </html>
  )
}
