### Create product
POST http://localhost:8005/products
Content-Type: application/json

{
    "name": "Banana",
    "description": "Banana Description",
    "price": 200
}

### Get Products
GET http://localhost:8005/products
Content-Type: application/json

### Get Products
GET http://localhost:8005/products?status=available
Content-Type: application/json